# Homework 10:

For questions 1-4 use the orthologs.sqlite database we created in class (include the database in the directory with the homework when returning it to github).

__Exercise 1.__ Create a query that will return the gene name, cai value and sequence for all yeast genes with CAI values larger than 0.85.

In [20]:
import sqlite3 as sql
# connecting to the database
con = sql.connect("orthologs.sqlite")

cur = con.cursor()

import pandas as pd
import plotly.graph_objs as go
import plotly.express as px

pd.read_sql('SELECT * FROM sequences', con)

pd.read_sql('SELECT gene_name, seq, CAI FROM sequences, CAI WHERE cai.title = sequences.gene_name AND CAI > 0.85', con)

   gene_name                                                seq    CAI
0    YAL038W  ATGTCTAGATTAGAAAGATTGACCTCATTAAACGTTGTTGCTGGTT...  0.893
1    YBR118W  ATGGGTAAAGAGAAGTCTCACATTAACGTTGTCGTTATCGGTCATG...  0.876
2    YGL030W  ATGGCCCCAGTTAAATCCCAAGAATCTATCAACCAAAAGTTGGCTT...  0.865
3    YGR192C  ATGGTTAGAGTTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...  0.924
4    YGR254W  ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...  0.871
5    YHR174W  ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...  0.892
6    YJL052W  ATGATCAGAATTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...  0.856
7    YJL189W  ATGGCTGCTCAAAAGTCTTTCAGAATCAAGCAAAAAATGGCTAAGG...  0.915
8    YJR009C  ATGGTTAGAGTTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...  0.905
9    YKL060C  ATGGGTGTTGAACAAATCTTAAAGAGAAAGACCGGTGTCATCGTTG...  0.869
10   YLR044C  ATGTCTGAAATTACTTTGGGTAAATATTTGTTCGAAAGATTAAAGC...  0.904
11   YLR061W  ATGGCCCCAAACACTTCCAGAAAGCAAAAGATTGCCAAGACCTTTA...  0.859
12   YLR110C  ATGCAATTTTCTACTGTCGCTTCTATCGCCGCTGTCGCCGCTGTCG...  0.870
13   YPR043W  ATGGCTAAAAGAACTAAGAAGGTTGGTATCACTGGTAAGTACGGTG...  0.872
14   YPR080W  ATGGGTAAAGAGAAGTCTCACATTAACGTTGTCGTTATCGGTCATG...  0.871

__Exercise 2.__ Modify the query above to return the gene name in yeast, the gene names in the other three species, the cai value and the sequence for all yeat genes with a cai value larger that 0.8 and that have orthologs in the other three species.

In [21]:
pd.read_sql('''
SELECT s.gene_name, s.seq, c.CAI, o.mikatae, o.paradoxus, o.bayanus FROM sequences s
JOIN cai c ON c.title = s.gene_name
JOIN orthologs o on s.gene_name = o.cerevisiae
WHERE c.CAI > 0.8
''',
con)

,gene_name,seq,CAI,mikatae,paradoxus,bayanus
0,YAL038W,ATGTCTAGATTAGAAAGATTGACCTCATTAAACGTTGTTGCTGGTT...,0.893,133,366,146
1,YBR181C,ATGAAGTTGAACATTTCTTACCCAGTCAACGGGTCTCAAAAGACCT...,0.846,575,1733,1653
2,YCR012W,ATGTCTTTATCTTCAAAGTTGTCTGTCCAAGATTTGGACTTGAAGG...,0.815,2014,2464,2653
3,YCR031C,ATGTCTAACGTTGTTCAAGCTCGTGACAATTCCCAAGTTTTTGGTG...,0.805,1948,2539,2721
4,YEL034W,ATGTCTGACGAAGAACATACCTTTGAAACTGCTGACGCTGGTTCCT...,0.814,5747,5869,6110
5,YGL123W,ATGTCTGCTCCAGAAGCTCAACAACAAAAGAGAGGTGGTTTCGGTG...,0.801,8023,8791,8164
6,YGL135W,ATGTCTAAGATCACCTCTTCTCAAGTCAGAGAACACGTCAAGGAAT...,0.832,8073,8842,8219
7,YGR254W,ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...,0.871,9167,9320,9559
8,YHL015W,ATGTCTGACTTTCAAAAGGAAAAGGTTGAAGAACAAGAACAACAAC...,0.827,9576,10453,23293
9,YHL033C,ATGGCCCCAGGTAAGAAAGTCGCTCCAGCTCCATTCGGTGCTAAGT...,0.842,9483,10537,10119
10,YHR174W,ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...,0.892,10272,9737,10953
11,YJL052W,ATGATCAGAATTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...,0.856,12006,11467,7692
12,YJL190C,ATGACCAGATCTTCCGTTTTAGCTGATGCTTTGAATGCCATTAACA...,0.812,11505,12007,12309
13,YJR123W,ATGTCTGACACCGAAGCTCCAGTTGAAGTTCAAGAAGATTTCGAAG...,0.838,12651,12748,13807
14,YKL060C,ATGGGTGTTGAACAAATCTTAAAGAGAAAGACCGGTGTCATCGTTG...,0.869,13447,13709,14543
15,YKL152C,ATGCCAAAGTTAGTTTTAGTTAGACACGGTCAATCCGAATGGAACG...,0.811,13136,14038,14168
16,YLR355C,ATGTTGAGAACTCAAGCCGCCAGATTGATCTGCAACTCCCGTGTCA...,0.802,15884,15522,16470
17,YML024W,ATGGGTAGAGTTAGAACCAAGACCGTCAAGCGTGCTTCTAAGGCTT...,0.810,16317,17429,17865
18,YOL039W,ATGAAGTACTTAGCTGCTTACCTATTATTGAACGCTGCTGGTAACA...,0.804,19423,20163,22682
19,YOL086C,ATGTCTATCCCAGAAACTCAAAAAGGTGTTATCTTCTACGAATCCC...,0.811,19645,19978,22315
20,YOL120C,ATGGGTATCGATCACACTTCCAAGCAACACAAGAGATCTGGTCACA...,0.812,19772,19865,22100
21,YOR063W,ATGTCTCACAGAAAGTACGAAGCACCACGTCACGGTCATTTAGGTT...,0.830,19967,20560,22996
22,YOR369C,ATGTCTGACGTTGAAGAAGTCGTTGAAGTTCAAGAAGAAACTGTTG...,0.844,20601,21712,24125
23,YPL090C,ATGAAGTTGAACATTTCTTACCCAGTTAACGGGTCTCAAAAGACCT...,0.837,21951,22560,25232
24,YPL131W,ATGGCTTTCCAAAAAGACGCTAAGTCCTCTGCTTACTCCTCTCGTT...,0.830,21794,22413,25389
25,YPL220W,ATGTCCAAGATCACTTCTTCTCAAGTCAGAGAACACGTCAAGGAAT...,0.821,21446,22041,24818
26,YPR080W,ATGGGTAAAGAGAAGTCTCACATTAACGTTGTCGTTATCGGTCATG...,0.871,22559,23137,25835

__Exercise 3.__ Perform the same query as above, but this time include the chromosome number of the gene in the output.

In [22]:
pd.read_sql('''
SELECT g.chrom, s.gene_name, s.seq, c.CAI, o.mikatae, o.paradoxus, o.bayanus FROM sequences s
JOIN cai c ON c.title = s.gene_name
JOIN orthologs o on s.gene_name = o.cerevisiae
JOIN gff g on s.gene_name = g.acc
WHERE c.CAI > 0.8
''',
con)

,chrom,gene_name,seq,CAI,mikatae,paradoxus,bayanus
0,chrI,YAL038W,ATGTCTAGATTAGAAAGATTGACCTCATTAAACGTTGTTGCTGGTT...,0.893,133,366,146
1,chrII,YBR181C,ATGAAGTTGAACATTTCTTACCCAGTCAACGGGTCTCAAAAGACCT...,0.846,575,1733,1653
2,chrIII,YCR012W,ATGTCTTTATCTTCAAAGTTGTCTGTCCAAGATTTGGACTTGAAGG...,0.815,2014,2464,2653
3,chrIII,YCR031C,ATGTCTAACGTTGTTCAAGCTCGTGACAATTCCCAAGTTTTTGGTG...,0.805,1948,2539,2721
4,chrV,YEL034W,ATGTCTGACGAAGAACATACCTTTGAAACTGCTGACGCTGGTTCCT...,0.814,5747,5869,6110
5,chrVII,YGL123W,ATGTCTGCTCCAGAAGCTCAACAACAAAAGAGAGGTGGTTTCGGTG...,0.801,8023,8791,8164
6,chrVII,YGL135W,ATGTCTAAGATCACCTCTTCTCAAGTCAGAGAACACGTCAAGGAAT...,0.832,8073,8842,8219
7,chrVII,YGR254W,ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...,0.871,9167,9320,9559
8,chrVIII,YHL015W,ATGTCTGACTTTCAAAAGGAAAAGGTTGAAGAACAAGAACAACAAC...,0.827,9576,10453,23293
9,chrVIII,YHL033C,ATGGCCCCAGGTAAGAAAGTCGCTCCAGCTCCATTCGGTGCTAAGT...,0.842,9483,10537,10119
10,chrVIII,YHR174W,ATGGCTGTCTCTAAAGTTTACGCTAGATCCGTCTACGACTCCCGTG...,0.892,10272,9737,10953
11,chrX,YJL052W,ATGATCAGAATTGCTATTAACGGTTTCGGTAGAATCGGTAGATTGG...,0.856,12006,11467,7692
12,chrX,YJL190C,ATGACCAGATCTTCCGTTTTAGCTGATGCTTTGAATGCCATTAACA...,0.812,11505,12007,12309
13,chrX,YJR123W,ATGTCTGACACCGAAGCTCCAGTTGAAGTTCAAGAAGATTTCGAAG...,0.838,12651,12748,13807
14,chrXI,YKL060C,ATGGGTGTTGAACAAATCTTAAAGAGAAAGACCGGTGTCATCGTTG...,0.869,13447,13709,14543
15,chrXI,YKL152C,ATGCCAAAGTTAGTTTTAGTTAGACACGGTCAATCCGAATGGAACG...,0.811,13136,14038,14168
16,chrXII,YLR355C,ATGTTGAGAACTCAAGCCGCCAGATTGATCTGCAACTCCCGTGTCA...,0.802,15884,15522,16470
17,chrXIII,YML024W,ATGGGTAGAGTTAGAACCAAGACCGTCAAGCGTGCTTCTAAGGCTT...,0.810,16317,17429,17865
18,chrXV,YOL039W,ATGAAGTACTTAGCTGCTTACCTATTATTGAACGCTGCTGGTAACA...,0.804,19423,20163,22682
19,chrXV,YOL086C,ATGTCTATCCCAGAAACTCAAAAAGGTGTTATCTTCTACGAATCCC...,0.811,19645,19978,22315
20,chrXV,YOL120C,ATGGGTATCGATCACACTTCCAAGCAACACAAGAGATCTGGTCACA...,0.812,19772,19865,22100
21,chrXV,YOR063W,ATGTCTCACAGAAAGTACGAAGCACCACGTCACGGTCATTTAGGTT...,0.830,19967,20560,22996
22,chrXV,YOR369C,ATGTCTGACGTTGAAGAAGTCGTTGAAGTTCAAGAAGAAACTGTTG...,0.844,20601,21712,24125
23,chrXVI,YPL090C,ATGAAGTTGAACATTTCTTACCCAGTTAACGGGTCTCAAAAGACCT...,0.837,21951,22560,25232
24,chrXVI,YPL131W,ATGGCTTTCCAAAAAGACGCTAAGTCCTCTGCTTACTCCTCTCGTT...,0.830,21794,22413,25389
25,chrXVI,YPL220W,ATGTCCAAGATCACTTCTTCTCAAGTCAGAGAACACGTCAAGGAAT...,0.821,21446,22041,24818
26,chrXVI,YPR080W,ATGGGTAAAGAGAAGTCTCACATTAACGTTGTCGTTATCGGTCATG...,0.871,22559,23137,25835

__Exercise 4.__ Now generate a table with the number of genes per chromosome that have CAI larger than 0.5 and have orthologs in the other three yeast species.

In [15]:
pd.read_sql('''
SELECT g.chrom, COUNT(s.gene_name) AS number_of_genes FROM sequences s
JOIN cai c ON c.title = s.gene_name
JOIN orthologs o on s.gene_name = o.cerevisiae
JOIN gff g on s.gene_name = g.acc
WHERE c.CAI > 0.5
GROUP BY g.chrom
''',
con)

      chrom  number_of_genes
0      chrI                3
1     chrII               12
2    chrIII                2
3     chrIV               11
4     chrIX                3
5      chrV               11
6     chrVI                5
7    chrVII               16
8   chrVIII                6
9      chrX               11
10    chrXI                6
11   chrXII               11
12  chrXIII                6
13   chrXIV                5
14    chrXV               15
15   chrXVI               10

__Exercise 5:__ Use the yeast genome gff file that we downloaded in class.

Read about the gff format and write a script that will create a database table with all the yeast genes and chromosomes. GFF files have all the annotation for a genome. For simplicity in our table we are only interested in the lines of the GFF files that give the coordinates of the chromosomes, genes, and tRNA genes. Your table should have the following columns: `ID number, Chromosome number, Start Position, End Position, Strand, Feature, Description`.

All this information should be readily available from the gff file, with the exception of the ID number, which is given as the "ID" in the last column, and you will have to process it a little bit. Again, only include in your table the yeast protein coding genes, tRNA coding genes, and chromosomes. Your final table should have one row per gene for a total of 6,923 rows.

Note that the description of several genes, and even some gene names contain special HTML characters, like %20. To convert these to text you should use the `unquote()` function of the `urllib` package. Do that before trying to use your regular expressions.

In [94]:
from urllib.parse import unquote
import pandas as pd
import numpy as np

data = {
    "ID number" : [],
    "Chromosome number" : [],
    "Start Position" : [],
    "End Position" : [],
    "Strand" : [],
    "Feature" : [],
    "Description": []
}

def parse(column):
    column_dict = {}
    for info in column.split(";"):
        key, value = info.split("=")
        column_dict[key] = unquote(value)
    return column_dict

with open("saccharomyces_cerevisiae_R64-3-1_20210421.gff") as file:
    for line in file:
        if line.startswith("#") or line.strip() == '':
            continue # skip any headers or empty lines
        columns = line.strip().split("\t") # seperate each line into a list of tab seperated parts
        if len(columns) < 9:
            continue
        if columns[2] in ["chromsome","gene","tRNA_gene"]:
            info = parse(columns[8])
            data["ID number"].append(info.get("ID", np.nan))
            data["Chromosome number"].append(columns[0])
            data["Start Position"].append(int(columns[3]))
            data["End Position"].append(int(columns[4]))
            data["Strand"].append(columns[6])
            data["Feature"].append(columns[2]),
            data["Description"].append(info.get("Note",np.nan))
            
df = pd.DataFrame(data)

df.to_csv("gff_new_table.gff", index=False, sep='\t')

df.to_sql("gff_new_table", con, index=False, if_exists="replace")

6906

In [97]:
df

,ID number,Chromosome number,Start Position,End Position,Strand,Feature,Description
0,YAL069W,chrI,335,649,+,gene,Dubious open reading frame; unlikely to encode...
1,YAL068W-A,chrI,538,792,+,gene,Dubious open reading frame; unlikely to encode...
2,YAL068C,chrI,1807,2169,-,gene,Protein of unknown function; member of the ser...
3,YAL067W-A,chrI,2480,2707,+,gene,Putative protein of unknown function; identifi...
4,YAL067C,chrI,7235,9016,-,gene,Putative permease; member of the allantoate tr...
...,...,...,...,...,...,...,...
6901,YNCQ0024C,chrmt,78089,78162,-,tRNA_gene,Mitochondrial threonine tRNA (tRNA-Thr); decod...
6902,YNCQ0025W,chrmt,78533,78608,+,tRNA_gene,Mitochondrial valine tRNA (tRNA-Val); predicte...
6903,Q0275,chrmt,79213,80022,+,gene,Subunit III of cytochrome c oxidase (Complex I...
6904,YNCQ0026W,chrmt,85035,85112,+,tRNA_gene,Mitochondrial formylated methionine tRNA (tRNA...
6905,Q0297,chrmt,85554,85709,+,gene,Dubious open reading frame; unlikely to encode...